"""add balcao column to atendentes

Revision ID: e1befa2ab1b0
Revises: ec25a1fe7c86
Create Date: 2026-02-26 22:13:52.180643

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1befa2ab1b0'
down_revision = 'ec25a1fe7c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atendentes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balcao', sa.Integer(), nullable=True, comment='Número do balcão do atendente'))

    with op.batch_alter_table('log_actividades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_atendente_id'))
        batch_op.drop_index(batch_op.f('ix_log_senha_id'))
        batch_op.create_index(batch_op.f('ix_log_actividades_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_actividades_atendente_id'), ['atendente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_actividades_senha_id'), ['senha_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('log_actividades_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'senhas', ['senha_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('senhas', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=mysql.VARCHAR(length=20),
               comment='Número da senha (ex: N001, P001)',
               existing_nullable=False)
        batch_op.alter_column('data_emissao',
               existing_type=sa.DATE(),
               comment='Data da emissão (para controle de numeração diária)',
               existing_nullable=False,
               existing_server_default=sa.text('(curdate())'))
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(length=20),
               comment='Tipo: normal ou prioritaria',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'"))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               comment='Status: aguardando, chamando, atendendo, concluida, cancelada',
               existing_nullable=False,
               existing_server_default=sa.text("'aguardando'"))
        batch_op.alter_column('emitida_em',
               existing_type=mysql.DATETIME(),
               comment='Data/hora de emissão (timestamp completo)',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('chamada_em',
               existing_type=mysql.DATETIME(),
               comment='Data/hora que senha foi chamada',
               existing_nullable=True)
        batch_op.alter_column('atendimento_iniciado_em',
               existing_type=mysql.DATETIME(),
               comment='Data/hora início do atendimento',
               existing_nullable=True)
        batch_op.alter_column('atendimento_concluido_em',
               existing_type=mysql.DATETIME(),
               comment='Data/hora fim do atendimento',
               existing_nullable=True)
        batch_op.alter_column('tempo_espera_minutos',
               existing_type=mysql.INTEGER(),
               comment='Tempo entre emissão e início (em minutos)',
               existing_nullable=True)
        batch_op.alter_column('tempo_atendimento_minutos',
               existing_type=mysql.INTEGER(),
               comment='Tempo entre início e fim (em minutos)',
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.drop_index(batch_op.f('idx_atendente_status'))
        batch_op.drop_index(batch_op.f('idx_servico_data_status'))
        batch_op.drop_index(batch_op.f('idx_tipo_emitida'))
        batch_op.drop_index(batch_op.f('ix_senhas_atendente_id'))
        batch_op.create_table_comment(
        'Senhas de atendimento com numeração diária',
        existing_comment=None
    )

    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment=None,
               existing_comment='Nome do serviço',
               existing_nullable=False)
        batch_op.alter_column('descricao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment=None,
               existing_comment='Descrição detalhada do serviço',
               existing_nullable=True)
        batch_op.alter_column('tempo_medio_minutos',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Tempo médio de atendimento em minutos',
               existing_nullable=False)
        batch_op.alter_column('icone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment=None,
               existing_comment='Emoji ou código de ícone para UI',
               existing_nullable=True)
        batch_op.alter_column('ordem_exibicao',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Ordem de exibição na interface (1=primeiro)',
               existing_nullable=False)
        batch_op.alter_column('ativo',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Se o serviço está ativo',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Data de criação do registro',
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Data da última atualização',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               comment='Data da última atualização',
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               comment='Data de criação do registro',
               existing_nullable=False)
        batch_op.alter_column('ativo',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Se o serviço está ativo',
               existing_nullable=False)
        batch_op.alter_column('ordem_exibicao',
               existing_type=mysql.INTEGER(),
               comment='Ordem de exibição na interface (1=primeiro)',
               existing_nullable=False)
        batch_op.alter_column('icone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               comment='Emoji ou código de ícone para UI',
               existing_nullable=True)
        batch_op.alter_column('tempo_medio_minutos',
               existing_type=mysql.INTEGER(),
               comment='Tempo médio de atendimento em minutos',
               existing_nullable=False)
        batch_op.alter_column('descricao',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               comment='Descrição detalhada do serviço',
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               comment='Nome do serviço',
               existing_nullable=False)

    with op.batch_alter_table('senhas', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='Senhas de atendimento com numeração diária'
    )
        batch_op.create_index(batch_op.f('ix_senhas_atendente_id'), ['atendente_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_tipo_emitida'), ['tipo', 'emitida_em'], unique=False)
        batch_op.create_index(batch_op.f('idx_servico_data_status'), ['servico_id', 'data_emissao', 'status'], unique=False)
        batch_op.create_index(batch_op.f('idx_atendente_status'), ['atendente_id', 'status'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('tempo_atendimento_minutos',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Tempo entre início e fim (em minutos)',
               existing_nullable=True)
        batch_op.alter_column('tempo_espera_minutos',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='Tempo entre emissão e início (em minutos)',
               existing_nullable=True)
        batch_op.alter_column('atendimento_concluido_em',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Data/hora fim do atendimento',
               existing_nullable=True)
        batch_op.alter_column('atendimento_iniciado_em',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Data/hora início do atendimento',
               existing_nullable=True)
        batch_op.alter_column('chamada_em',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Data/hora que senha foi chamada',
               existing_nullable=True)
        batch_op.alter_column('emitida_em',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Data/hora de emissão (timestamp completo)',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='Status: aguardando, chamando, atendendo, concluida, cancelada',
               existing_nullable=False,
               existing_server_default=sa.text("'aguardando'"))
        batch_op.alter_column('tipo',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='Tipo: normal ou prioritaria',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'"))
        batch_op.alter_column('data_emissao',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data da emissão (para controle de numeração diária)',
               existing_nullable=False,
               existing_server_default=sa.text('(curdate())'))
        batch_op.alter_column('numero',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='Número da senha (ex: N001, P001)',
               existing_nullable=False)

    with op.batch_alter_table('log_actividades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('log_actividades_ibfk_1'), 'senhas', ['senha_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_log_actividades_senha_id'))
        batch_op.drop_index(batch_op.f('ix_log_actividades_atendente_id'))
        batch_op.drop_index(batch_op.f('ix_log_actividades_acao'))
        batch_op.create_index(batch_op.f('ix_log_senha_id'), ['senha_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_atendente_id'), ['atendente_id'], unique=False)

    with op.batch_alter_table('atendentes', schema=None) as batch_op:
        batch_op.drop_column('balcao')

    # ### end Alembic commands ###
