"""Criar tabelas conforme MER corrigido

Revision ID: ec25a1fe7c86
Revises: 
Create Date: 2026-02-07 16:48:54.631614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec25a1fe7c86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendentes',
    sa.Column('nome', sa.String(length=150), nullable=False, comment='Nome completo do atendente'),
    sa.Column('email', sa.String(length=150), nullable=False, comment='Email (usado para login)'),
    sa.Column('senha_hash', sa.String(length=255), nullable=False, comment='Senha criptografada com bcrypt'),
    sa.Column('tipo', sa.Enum('admin', 'atendente'), nullable=False, comment='Tipo: admin ou atendente'),
    sa.Column('balcao', sa.Integer(), nullable=True, comment='Número do balcão (1, 2, 3) ou NULL se admin'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Se o atendente está ativo'),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True, comment='Data do último login'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data da última atualização'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atendentes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atendentes_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_atendentes_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_atendentes_tipo'), ['tipo'], unique=False)

    op.create_table('configuracoes',
    sa.Column('chave', sa.String(length=100), nullable=False, comment='Nome único da configuração'),
    sa.Column('valor', sa.Text(), nullable=False, comment='Valor da configuração (sempre string, converter depois)'),
    sa.Column('tipo', sa.Enum('string', 'int', 'boolean'), nullable=False, comment='Tipo do valor: string, int ou boolean'),
    sa.Column('descricao', sa.Text(), nullable=True, comment='Descrição da configuração'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data da última atualização'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_chave'), ['chave'], unique=True)

    op.create_table('servicos',
    sa.Column('nome', sa.String(length=100), nullable=False, comment='Nome do serviço'),
    sa.Column('descricao', sa.Text(), nullable=True, comment='Descrição detalhada do serviço'),
    sa.Column('tempo_medio_minutos', sa.Integer(), nullable=False, comment='Tempo médio de atendimento em minutos'),
    sa.Column('icone', sa.String(length=50), nullable=True, comment='Emoji ou código de ícone para UI'),
    sa.Column('ordem_exibicao', sa.Integer(), nullable=False, comment='Ordem de exibição na interface (1=primeiro)'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Se o serviço está ativo'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data da última atualização'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicos_ativo'), ['ativo'], unique=False)

    op.create_table('senhas',
    sa.Column('numero', sa.String(length=20), nullable=False, comment='Número único da senha (ex: N001, P005)'),
    sa.Column('tipo', sa.Enum('normal', 'prioritaria'), nullable=False, comment='Tipo: normal ou prioritaria'),
    sa.Column('status', sa.Enum('aguardando', 'chamando', 'atendendo', 'concluida', 'cancelada'), nullable=False, comment='Status atual da senha'),
    sa.Column('servico_id', sa.Integer(), nullable=False, comment='Serviço solicitado'),
    sa.Column('atendente_id', sa.Integer(), nullable=True, comment='Atendente que realizou o atendimento'),
    sa.Column('numero_balcao', sa.Integer(), nullable=True, comment='Número do balcão (1, 2, 3, 4...)'),
    sa.Column('usuario_contato', sa.String(length=20), nullable=True, comment='Telefone do utente (OPCIONAL, para SMS futuro)'),
    sa.Column('emitida_em', sa.DateTime(), nullable=False, comment='Momento da emissão'),
    sa.Column('chamada_em', sa.DateTime(), nullable=True, comment='Momento em que foi chamada'),
    sa.Column('atendimento_iniciado_em', sa.DateTime(), nullable=True, comment='Início do atendimento'),
    sa.Column('atendimento_concluido_em', sa.DateTime(), nullable=True, comment='Fim do atendimento'),
    sa.Column('tempo_espera_minutos', sa.Integer(), nullable=True, comment='Tempo de espera em minutos (calculado)'),
    sa.Column('tempo_atendimento_minutos', sa.Integer(), nullable=True, comment='Duração do atendimento em minutos (calculado)'),
    sa.Column('observacoes', sa.Text(), nullable=True, comment='Observações do atendente'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data da última atualização'),
    sa.ForeignKeyConstraint(['atendente_id'], ['atendentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('senhas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_senhas_atendente_id'), ['atendente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_senhas_emitida_em'), ['emitida_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_senhas_numero'), ['numero'], unique=True)
        batch_op.create_index(batch_op.f('ix_senhas_servico_id'), ['servico_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_senhas_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_senhas_tipo'), ['tipo'], unique=False)

    op.create_table('log_actividades',
    sa.Column('senha_id', sa.Integer(), nullable=True, comment='Senha relacionada'),
    sa.Column('atendente_id', sa.Integer(), nullable=True, comment='Atendente que realizou a ação'),
    sa.Column('acao', sa.String(length=50), nullable=False, comment='Tipo de ação (emitida, chamada, iniciada, concluida, cancelada)'),
    sa.Column('descricao', sa.Text(), nullable=True, comment='Descrição detalhada da ação'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Endereço IP de origem'),
    sa.Column('user_agent', sa.String(length=255), nullable=True, comment='Navegador/dispositivo'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Data de criação do registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Data da última atualização'),
    sa.ForeignKeyConstraint(['atendente_id'], ['atendentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['senha_id'], ['senhas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_actividades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_actividades_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_actividades_atendente_id'), ['atendente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_actividades_senha_id'), ['senha_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_actividades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_actividades_senha_id'))
        batch_op.drop_index(batch_op.f('ix_log_actividades_atendente_id'))
        batch_op.drop_index(batch_op.f('ix_log_actividades_acao'))

    op.drop_table('log_actividades')
    with op.batch_alter_table('senhas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_senhas_tipo'))
        batch_op.drop_index(batch_op.f('ix_senhas_status'))
        batch_op.drop_index(batch_op.f('ix_senhas_servico_id'))
        batch_op.drop_index(batch_op.f('ix_senhas_numero'))
        batch_op.drop_index(batch_op.f('ix_senhas_emitida_em'))
        batch_op.drop_index(batch_op.f('ix_senhas_atendente_id'))

    op.drop_table('senhas')
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicos_ativo'))

    op.drop_table('servicos')
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_chave'))

    op.drop_table('configuracoes')
    with op.batch_alter_table('atendentes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atendentes_tipo'))
        batch_op.drop_index(batch_op.f('ix_atendentes_email'))
        batch_op.drop_index(batch_op.f('ix_atendentes_ativo'))

    op.drop_table('atendentes')
    # ### end Alembic commands ###
